dist: xenial
language: cpp
compiler:
  - g++-8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - cmake

before_install:
  - sudo apt-get install gcc-8 g++-8
  - export CXX=g++-8
  - git clone https://github.com/cdsama/vcpkg.git
  - cd vcpkg
  - ./bootstrap-vcpkg.sh
  - export VCPKG_ROOT="$(pwd -P)"
  - cd ..

install:
  - cd vcpkg
  - ./vcpkg install catch2
  - cd ..

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build ./
  - cd ..

