dist: xenial
language: cpp
compiler:
  - g++-8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-8
    - cmake

before_install:
  - export CC=gcc-8
  - export CXX=g++-8
  - export GCOV=gcov-8
  - bash ./build_scripts/build_vcpkg.sh
  - export VCPKG_ROOT="$(pwd -P)/vcpkg"
  - export PATH="${PATH}:${VCPKG_ROOT}"

install:
  - vcpkg install catch2

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build ./
  - ./unittest
  - cd ..

cache:
  directories:
  - vcpkg

after_success:
  - cd build
  - bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov) -x $GCOV -a "-s `pwd`" >/dev/null 2>&1 && echo "Codecov success" || echo "Codecov did not collect coverage reports"
  - cd ..
